version: '3.8'

services:
  app:
    image: tripzin/elegant-tex-app:v1.0.3
    container_name: elegant-tex-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - elegant-tex-network


  nginx:
    image: nginx:latest
    container_name: elegant-tex-server
    restart: unless-stopped
    volumes:
      - ./.docker/nginx/nginx.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - elegant-tex-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email jafrultripto@gmail.com -d elegant-tex.com --agree-tos

  db:
    image: mysql:8.0.33
    container_name: elegant-tex-db
    restart: unless-stopped
    environment:
      TZ: Asia/Dhaka
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - elegant-tex-network

networks:
  elegant-tex-network:
    driver: bridge
volumes:
  db-data: ~
