name: ElegantTex CI

on:
  push:
    branches:
      - "stage"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install --prefix frontend/
      - run: npm run build:staging --prefix frontend/
